#!/usr/bin/env zsh
# copy specific files from ~/.config/nvim to ./config/nvim
cp $HOME/.config/nvim/init.lua ./config/nvim/init.lua
cp -r $HOME/.config/nvim/lua/hyunchel/* ./config/nvim/lua/hyunchel/
cp -r $HOME/.config/nvim/after/* ./config/nvim/after/
cp -r $HOME/.config/nvim/ftplugin/* ./config/nvim/ftplugin/
cp -r $HOME/.config/xmonad/xmonad.hs ./config/xmonad/
cp -r $HOME/.config/xmonad/xmobarrc ./config/xmonad/
