#!/usr/bin/env bash
# copy specific files from ~/.config/nvim to ./config/nvim
cp $HOME/.config/nvim/init.lua ./config/nvim/init.lua
cp -r $HOME/.config/nvim/lua/hyunchel/* ./config/nvim/lua/hyunchel/
cp -r $HOME/.config/nvim/after/* ./config/nvim/after/
