#!/usr/bin/env zsh

BASE=$(pwd)
PLATFORM=$(uname -s)

# dotfiles
ln -sfv "$BASE/zshrc" ~/.zshrc
ln -sfv "$BASE/zshenv" ~/.zshenv
ln -sfv "$BASE/zsh" ~/.zsh
ln -sfv "$BASE/tmux.conf" ~/.tmux.conf
ln -sfv "$BASE/gitignore" ~/.gitignore
ln -sfv "$BASE/xinitrc" ~/.xinitrc
ln -sfv "$BASE/config/nvim" ~/.config/nvim
ln -sfv "$BASE/bin/" ~/bin

# kitty
mkdir -p ~/.config/kitty
ln -sfv "$BASE/config/kitty/kitty.conf" ~/.config/kitty/kitty.conf

# tmux
mkdir -p ~/.tmux/plugins
git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

# taskwarrior
mkdir -p ~/.config/task/hooks
cp "$BASE/ext/on-modify.timewarrior" ~/.task/hooks/

# Git hooks
cp "$BASE/gitconfig" ~/.gitconfig
rm -rf ~/.git_template
ln -sfv "$BASE/git_template" ~/.git_template
git config --global init.templatedir '~/.git_template'
git config --global alias.ctags '!.git/hooks/ctags'

# applies nvim, hypr, waybar local configs to the system
. "$BASE/apply-source"

# zsh-z plugin
if [ ! -e ~/.zsh/zsh-z.plugin.zsh ]; then
    curl https://raw.githubusercontent.com/agkozak/zsh-z/master/zsh-z.plugin.zsh -o ~/.zsh/zsh-z.plugin.zsh
fi

# Linux
if [ "$PLATFORM" = Linux ]; then
    # nvm
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash

    # neovim
    curl -LO https://github.com/neovim/neovim/releases/latest/download/nvim.appimage
    chmod u+x nvim.appimage
    sudo mv nvim.appimage /usr/bin/nvim

    # ctags
    sudo apt-get install -y gcc ctags

    # fzf
    git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
    ~/.fzf/install     
fi

# Darwin
if [ "$PLATFORM" = Darwin ]; then
    [ -z "$(which brew)" ] &&
        /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    eval "$(/opt/homebrew/bin/brew shellenv)"

    brew install \
       cmake mono \
       neovim tmux go python \
       ripgrep \
       wget mosh jq tree pgcli \
       gnupg \
       redis pgcli mycli \
       httpie

    brew install fzf
    $(brew --prefix)/opt/fzf/install

    brew install --cask caffeine
    brew install --cask ngrok
fi
