#!/usr/bin/env bash

BASE=$(pwd)
PLATFORM=$(uname -s)

# dotfiles
ln -sfv "$BASE/bashrc" ~/.bashrc
ln -sfv "$BASE/bash_profile" ~/.bash_profile
ln -sfv "$BASE/vimrc" ~/.vimrc
ln -sfv "$BASE/tmux.conf" ~/.tmux.conf
ln -sfv "$BASE/gitconfig" ~/.gitconfig
ln -sfv "$BASE/gitignore" ~/.gitignore
# configs
ln -sfv "$BASE/config/pgcli/config" ~/.config/pgcli/config
ln -sfv "$BASE/config/mycli/config" ~/.myclirc

# Install VIM plugins
git clone https://github.com/fatih/vim-go.git ~/.vim/pack/plugins/start/vim-go

# Move VIM
mkdir -p ~/.vim
rm -rf ~/.vim/colors
ln -sfv "$BASE/colors" ~/.vim/colors

# Golang
mkdir -p ~/gosrc

# git-prompt
if [ ! -e ~/.git-prompt.sh ]; then
	curl https://raw.githubusercontent.com/git/git/master/contrib/completion/git-prompt.sh -o ~/.git-prompt.sh
fi

# git-completion
if [ ! -e ~/.git-completion.bash ]; then
	curl https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.bash -o ~/.git-completion.bash
fi


if [ "$PLATFORM" = Linux ]; then
    sudo apt-get install -y gcc ctags
fi

# Homebrew
if [ "$PLATFORM" = Darwin ]; then
    # We need Homebrew
    [ -z "$(which brew)" ] &&
        /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

    # Install favorite tools.
    brew install \
       vim go python \
       git wget mosh jq tree pgcli ctags \
       hugo

   # Some work stuff.
   # redis pgcli mycli \
   # httpie nvm kubernetes-cli kubernetes-helm
fi
