#!/usr/bin/env bash

BASE=$(pwd)
PLATFORM=$(uname -s)

# dotfiles
ln -sfv "$BASE/bashrc" ~/.bashrc
ln -sfv "$BASE/bash_profile" ~/.bash_profile
ln -sfv "$BASE/inputrc" ~/.inputrc
ln -sfv "$BASE/vimrc" ~/.vimrc
ln -sfv "$BASE/tmux.conf" ~/.tmux.conf
ln -sfv "$BASE/gitconfig" ~/.gitconfig
ln -sfv "$BASE/gitignore" ~/.gitignore
# configs
mkdir -p ~/.config/hyunchel
mkdir -p ~/.config/pgcli
mkdir -p ~/.config/mycli
ln -sfv "$BASE/config/pgcli/config" ~/.config/pgcli/config
ln -sfv "$BASE/config/mycli/config" ~/.myclirc

cp -r "$BASE/bin/" ~/bin/

# Install VIM plugins
git clone https://github.com/fatih/vim-go.git ~/.vim/pack/plugins/start/vim-go

# Move VIM
mkdir -p ~/.vim
rm -rf ~/.vim/colors
ln -sfv "$BASE/colors" ~/.vim/colors

# Golang
mkdir -p ~/gosrc

# git-prompt
if [ ! -e ~/.git-prompt.sh ]; then
	curl https://raw.githubusercontent.com/git/git/master/contrib/completion/git-prompt.sh -o ~/.git-prompt.sh
fi

# git-completion
if [ ! -e ~/.git-completion.bash ]; then
	curl https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.bash -o ~/.git-completion.bash
fi

# ZSH...

# Oh-my-zsh
# sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

# Install Powerline font(required by Spaceship)
# git clone https://github.com/powerline/fonts.git --depth=1
# cd fonts
# ./install.sh
# cd ..
# rm -rf fonts

# Install ZSH customs
# ln -sfv "$BASE/zsh/custom" ~/.oh-my-zsh/custom

# Overwrite ZSHRC
# ln -sfv "$BASE/zsh/zshrc" ~/.zshrc


# CTAGS
if [ "$PLATFORM" = Linux ]; then
    sudo apt-get install -y gcc ctags
fi

# Homebrew
if [ "$PLATFORM" = Darwin ]; then
    # We need Homebrew
    [ -z "$(which brew)" ] &&
        /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

    # Install favorite tools.
    brew install \
       bash-completion@2 \
       vim tmux go python \
       git wget mosh jq tree pgcli ctags \
       redis pgcli mycli \
       httpie nvm kubernetes-cli kubernetes-helm \
       hugo

    brew install --HEAD universal-ctags/universal-ctags/universal-ctags

    brew install fzf
    $(brew --prefix)/opt/fzf/install
fi
